# Basic
title: nkkk
subtitle: 个人站
description: welcome
# 头像里面的标题
avatarTitle: kk
# 头像里面的描述
avatarDesc: 无
url: "http://www.xiaobaozi.xyz"

# Comment
comment:
    disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: 无 
    github: inkpgk
    # twitter: 
    mail: 无

# 百度统计 
baidu:
      

# Google Analytics
ga:  
    host: auto  





permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


